# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=b'system', help_text='Who created this model', max_length=70)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_modified_by', models.CharField(default=b'system', help_text='Who modified this model', max_length=70)),
                ('name', models.TextField(help_text='Name of requestee', max_length=100)),
                ('message', models.TextField(help_text='Message of requestee', max_length=1000)),
                ('identifier', models.UUIDField(editable=False, help_text='Identifier of requestee', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
