# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160904_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='ignore',
            field=models.BooleanField(default=False, help_text='Ignore hello request'),
        ),
    ]
