# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_hello_ignore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='ignore',
        ),
        migrations.AddField(
            model_name='hello',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hello'), (900, 'Hello request blocked'), (100, 'Hello request accepted')], default=0, help_text='Hello request status'),
        ),
    ]
