# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20160913_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Mingle',
        ),
    ]
