language: python
python: 2.7

before_install:
    - pip install coveralls

install:
    - pip install -r requirements.txt

script:
    - pytest --maxfail=2 --cov . --cov-report=html

after_success:
    - coveralls