# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=b'system', help_text='Who created this model', max_length=70)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_modified_by', models.CharField(default=b'system', help_text='Who modified this model', max_length=70)),
                ('uuid', models.CharField(editable=False, help_text='Unique identifier', max_length=36, unique=True)),
                ('name', models.CharField(default=b'undefined', help_text='Name of this node', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Descriptive information', max_length=500)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
