# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=b'system', help_text='Who created this model', max_length=70)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_modified_by', models.CharField(default=b'system', help_text='Who modified this model', max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
